import JSZip from "jszip";
import {
  LabState,
  TraceFrame,
  buildPacketManifest,
  replayTrace,
  traceToJsonl,
  validateTrace
} from "./labEngine";

export async function exportSimulatedPacket(
  frames: TraceFrame[],
  state: LabState,
  sceneDataUrl: string | null
): Promise<Blob> {
  const zip = new JSZip();
  zip.file("simulated_trace.jsonl", traceToJsonl(frames));
  zip.file("validation_output.txt", validateTrace(frames));
  zip.file("replay_output.txt", replayTrace(frames));
  zip.file("PACKET_MANIFEST.json", JSON.stringify(buildPacketManifest(frames), null, 2));
  zip.file("wiring_snapshot.json", JSON.stringify(state, null, 2));
  zip.file(
    "FINDINGS.md",
    [
      "# MGElectronics Reflex Course Simulated Findings",
      "",
      "Status: simulated remote-lab evidence only.",
      "",
      "This packet was generated by the guided MGElectronics Three.js lab.",
      "It does not claim live hardware behavior, certified safety, or production readiness.",
      "",
      "Loop:",
      "",
      "```text",
      "potentiometer -> threshold_reflex_v0 -> guard clamp -> LED -> terminal trace -> replay",
      "```",
      "",
      `Frames: ${frames.length}`,
      "Source: mgelectronics_lab_sim",
      "Simulated: true",
      "Hardware observed: false",
      "Live serial capture performed: false",
      "Certified safety claim: false",
      "Production controller claim: false",
      ""
    ].join("\n")
  );

  if (sceneDataUrl?.startsWith("data:image/png;base64,")) {
    zip.file("scene_snapshot.png", sceneDataUrl.split(",")[1], { base64: true });
  } else {
    zip.file("scene_snapshot.png", "");
  }

  return zip.generateAsync({ type: "blob" });
}
